## This is Tasks Module/Routes Test file

####################
// 1. Get All Tasks
####################
GET http://localhost:3000/tasks
Content-Type: application/json

####################
// 2. Get Task By Id
#####################
GET http://localhost:3000/tasks/4398f26b-f527-4eeb-b74c-cd4c0ecc9060
Content-Type: application/json


#####################
// 3. Create New Task
######################
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "New Task"
}


##################
// 4. Update Task
#################
PATCH  http://localhost:3000/tasks/79bb106f-0ef5-4468-a06f-c11035d6607c
Content-Type: application/json

{
    "title": "Test Task Finale",
    "completed": true
}

###################
// 5. Delete Task
###################

DELETE  http://localhost:3000/tasks/:id
Content-Type: application/json